bin/publish fixes.

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -euUx -o pipefail;
+set -eu -o pipefail;
 
 readonly repo_dir="$( cd $(dirname ${BASH_SOURCE})/..; pwd )";
 
@@ -13,7 +13,7 @@ GIT_STATUS_LINES="$(git status --porcelain=v1 | tee /dev/stderr | wc -l)"
 if [ "${GIT_STATUS_LINES}" -ne "0" ]; then
     cat <<EOF
 
-Error: `git status` shows changes in the local worktree or git index.
+Error: 'git status' shows changes in the local worktree or git index.
 Commit or stash your changes.
 
 EOF
@@ -34,9 +34,9 @@ TAG_STATUS_LINES="$(echo "${TAG_STATUS}" | tee /dev/stderr | wc -l)"
 if [ "${TAG_STATUS_LINES}" -ne "1" ]; then
     cat <<EOF
 
-Error: No git tag `${TAG_NAME}` found for current package version.
+Error: No git tag '${TAG_NAME}' found for current package version.
 
-Try creating a tag with `git tag ${TAG_NAME}`.
+Try creating a tag with 'git tag ${TAG_NAME}'.
 
 EOF
     exit 1
@@ -67,9 +67,9 @@ TAG_ORIGIN_STATUS_LINES="$(echo "${TAG_ORIGIN_STATUS}" | tee /dev/stderr | wc -l
 if [ "${TAG_ORIGIN_STATUS_LINES}" -ne "1" ]; then
     cat <<EOF
 
-Error: git tag `${TAG_NAME}` not found on remote `origin`.
+Error: git tag '${TAG_NAME}' not found on remote 'origin'.
 
-Try pushing the tag with `git push origin tag ${TAG_NAME}`.
+Try pushing the tag with 'git push origin tag ${TAG_NAME}'.
 
 EOF
     exit 1
@@ -79,7 +79,7 @@ fi
 if [ "${TAG_ORIGIN_STATUS}" -ne "${TAG_STATUS}" ]; then
     cat <<EOF
 
-Error: Remote `origin`'s tag commit hash is wrong.
+Error: On remote 'origin' tag commit hash is wrong.
 
 The local tag does not match the remote tag.
 Either force update the local or remote tag.
